[DBC-213] Wallet list dialog
mvlchain/mvl-wallet-android pull request #20
Opened 2021-11-06 03:09 UTC by quocnd

## Description
- Implement UI for wallet list dialog

## Screenshots

![image](https://user-images.githubusercontent.com/10803943/140595987-c41e2cc9-67ac-46b6-b2e2-9c4ff8567def.png)

2021-11-09 01:21 UTC, cutehackers requested changes
Minor changes required.

2021-11-09 01:21 UTC, cutehackers commented on app/src/main/java/io/mvlchain/tada/wallet/app/ui/wallet/WalletListDialog.kt
> +class WalletListDialog : BaseBottomSheetDialogFragment<DialogWalletListBinding>() {
Rename this screen from `WalletListDialog` to `WalletListDialogFragment`

2021-11-09 01:22 UTC, cutehackers commented
I just wonder if the height of the WalletList can be dynamically changed?

2021-11-10 02:26 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/ui/wallet/WalletListDialog.kt
> +class WalletListDialog : BaseBottomSheetDialogFragment<DialogWalletListBinding>() {
Correct one, will change it

2021-11-10 02:49 UTC, quocnd commented
> I just wonder if the height of the WalletList can be dynamically changed?

It can be but we need to handle programmatically by Kotlin. It can't be arranged easily on layout. So I think we can improve this later
E.g:
- We can't use `layout_height="0"` because recyclerView is not visible with list
- If we use `layout_height="wrap_content"`: If the list exceeds screen height, the list will overlap other views.
![image](https://user-images.githubusercontent.com/10803943/141040545-637a1c78-286e-4672-b8f7-ad444d8cb368.png)

2021-11-10 04:41 UTC, cutehackers approved these changes
Okay great, Please leave a comment for the height of the wallet list recyclerview.

2021-11-10 07:19 UTC, merged