[DBC-229] [DBC-121] Create wallet, token sender
mvlchain/mvl-wallet-android pull request #25
Opened 2021-11-17 08:18 UTC by quocnd

## Description
- Implement create wallet and post address to backend
- Create transaction, transfer and upload txHash to backend

## Note
- Hardcoded rates

## Screenshots

2021-11-18 04:00 UTC, cutehackers requested changes

2021-11-18 04:00 UTC, cutehackers commented on app/src/main/java/io/mvlchain/tada/wallet/app/const/TokenTypeEnum.kt
> +enum class TokenTypeEnum constructor(
makes me confusing TokenType, TokenTypeEnum

2021-11-18 04:24 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/ui/tokensender/TokenSenderViewModel.kt
> +                            handleError(it.exception)
Yeah, It will be hidden via `onCompletion` for both cases: Success and Error

2021-11-18 04:24 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/ui/walletcreation/CreateWalletViewModel.kt
> +            registerWalletUseCase.invoke(request)
Noted

2021-11-18 04:25 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/ui/wallet/WalletViewModel.kt
> +                            _tokenList.value = it.data.sortedBy { wallet -> wallet.id }
Good catch, I think we can sort it via `WalletDao`

2021-11-18 04:26 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/ui/tokensender/TokenSenderFragment.kt
> +                BigDecimal(0)
Yes, correctly 😃

2021-11-18 04:27 UTC, quocnd commented on shared/src/main/java/io/mvlchain/tada/wallet/shared/data/repository/TransactionRepository.kt
> +            awaitClose { /*Do nothing*/ }
Cool, I will update that

2021-11-18 04:35 UTC, quocnd commented on shared/src/main/java/io/mvlchain/tada/wallet/shared/data/repository/TransactionRepository.kt
> +            walletService.postTransaction(txHash)
All exceptions will be catch via `FlowUseCase`. 
We can customize Exception by can try-catch if  we don't, we can let it be.
![image](https://user-images.githubusercontent.com/10803943/142352165-9e192f52-9260-4939-81b3-88ca77252935.png)

2021-11-18 04:43 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/ui/tokensender/TokenSenderFragment.kt
> +            binding.addressEdit.setText(getSenderAddress())
This case is quite special. In this case, I already have address. But can't display it on EditText immediately, because camera is closing, there is a trigger that makes the EditText clear the text.
I haven't figured out the root cause yet, this is a workaround that make it work.
It's not related to ViewModel as I can get address already.

2021-11-18 04:52 UTC, quocnd commented on wallet-core/src/main/java/io/mvlchain/tada/wallet/core/model/ClutchModel.kt
> +    fun getCoinPrivateKey(): PrivateKey {
1. Good recommendation with `internal getCoinPrivateKey(): PrivateKey {}`

2. between Clutch and ClutchModel => This is an interesting thing. I wanted to add more properties in Clutch but it effects many places. So I decided to create new one and refactor later :))

2021-11-18 04:59 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/const/NetworkInfo.kt
> +class NetworkInfo constructor(
Yeah, that's a better name

2021-11-18 05:00 UTC, quocnd commented on wallet-core/src/main/java/io/mvlchain/tada/wallet/core/util/SignatureUtil.kt
> +    }
Good idea, we can save a file

2021-11-18 05:57 UTC, quocnd commented on wallet-core/src/main/java/io/mvlchain/tada/wallet/core/service/Erc20TransferTransaction.kt
> +class Erc20TransferTransaction @Inject constructor() : WalletTransaction {
Seem it's clearer. Will change it

2021-11-18 06:00 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/const/TokenTypeEnum.kt
> +enum class TokenTypeEnum constructor(
Will check with a better name 👍

2021-11-18 06:01 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/ui/tokensender/TokenSenderViewModel.kt
> +                            handleError(it.exception)
Yeah, It will be hidden via onCompletion for both cases: Success and Error

2021-11-24 00:42 UTC, cutehackers commented on shared/src/main/java/io/mvlchain/tada/wallet/shared/data/repository/TransactionRepository.kt
> +            walletService.postTransaction(txHash)
Oh. yeap.

2021-11-24 00:50 UTC, cutehackers approved these changes

2021-11-24 01:49 UTC, merged