[DBC-122] Token list editor
mvlchain/mvl-wallet-android pull request #27
Opened 2021-11-18 10:12 UTC by quocnd

## Description
- Implement token list editor
- Change position of tokens
- Show/hide tokens

## Note

## Screenshots

https://user-images.githubusercontent.com/10803943/142395621-cd51a01c-3ff5-4dbf-8326-bf4b78717341.mp4

2021-11-23 02:58 UTC, cutehackers requested changes

2021-11-23 02:58 UTC, cutehackers commented on shared/src/main/java/io/mvlchain/tada/wallet/shared/data/repository/WalletRepository.kt
> +    }
It could be simple if you create a suspend method in this case, If it's a simple method like this so that you can simply wrap it with flow from a GetWalletUseCase 
```
class WalletRepository {
  override suspend fun getWallet(walletId: String): WalletModel { ... }
}

class GetWalletUseCase() {
  override fun execute(parameters: String): Flow<Resource<WalletModel>> {
    return flow {
     val result = repository.getWallets(parameters)
     emit(result)
    }
  }
}
```

2021-11-23 02:58 UTC, cutehackers commented on shared/src/main/java/io/mvlchain/tada/wallet/shared/data/repository/WalletRepository.kt
> +        }
Same as the above case?

2021-11-23 02:58 UTC, cutehackers commented on shared/src/main/java/io/mvlchain/tada/wallet/shared/domain/GetWalletUseCase.kt
> +            .getWallet(parameters)
Please refer to the above comments?

2021-11-23 02:58 UTC, cutehackers commented on shared/src/main/java/io/mvlchain/tada/wallet/shared/domain/UpdateBalancesUseCase.kt
> +            .updateBalances(parameters)
same as the above?

2021-11-23 02:58 UTC, cutehackers commented on shared/src/test/java/io/mvlchain/tada/wallet/shared/data/repository/WalletRepositoryImplTest.kt
> +class WalletRepositoryImplTest {
Room.inMemoryDatabaseBuilder can help test unit test for local db entities. 
You might already understand though,
```
/*
 * InstantTaskExecutorRule is a JUnit Test Rule that swaps the background executor used by the
 * Architecture Components with a different one which executes each task synchronously.
 */
@get:Rule
var instantTaskExecutorRule = InstantTaskExecutorRule()

// Overrides Dispatchers.Main used in Coroutines
@ExperimentalCoroutinesApi
@get:Rule
var coroutineRule = MainCoroutineRule()

private lateinit var db: AppDatabase
private lateinit var testDao: TestDao

@Before
fun setUp() {
    val context = ApplicationProvider.getApplicationContext<TestApplication>()
    val executor = coroutineRule.testDispatcher.asExecutor()
    db = Room.inMemoryDatabaseBuilder(context, AppDatabase::class.java)
        .allowMainThreadQueries()
        .setTransactionExecutor(executor)
        .setQueryExecutor(executor)
        .build()
    testDao = db.getTestDao()
}

@After
@Throws(IOException::class)
fun tearDown() {
    db.close()
}
```

2021-11-23 02:58 UTC, cutehackers commented on shared/src/main/java/io/mvlchain/tada/wallet/shared/data/db/entity/SimpleWalletEntity.kt
> +    @Embedded(prefix = "asset_")
We can improve this code by referring to following github sample that utilize @Embedded feature.(indexing and query)

[entity](https://github.com/android/architecture-components-samples/blob/main/GithubBrowserSample/app/src/main/java/com/android/example/github/vo/Repo.kt)
[dao](https://github.com/android/architecture-components-samples/blob/main/GithubBrowserSample/app/src/main/java/com/android/example/github/db/RepoDao.kt)
[repository](https://github.com/android/architecture-components-samples/blob/main/GithubBrowserSample/app/src/main/java/com/android/example/github/repository/RepoRepository.kt)

2021-11-23 07:44 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/base/IBaseFragment.kt
> +    fun observeResultListeners() = Unit
It may not, because it's `default method` in interface.
We can define either `fun observeResultListeners() {}` or `fun observeResultListeners() = Unit`

If we do like this: `fun observeResultListeners()`. We have to always override it

2021-11-23 07:47 UTC, quocnd commented on shared/src/main/java/io/mvlchain/tada/wallet/shared/data/db/AppDatabase.kt
> +    version = 2, exportSchema = false
Good catch, will revert it

2021-11-23 08:14 UTC, quocnd commented on shared/src/test/java/io/mvlchain/tada/wallet/shared/data/repository/WalletRepositoryImplTest.kt
> +class WalletRepositoryImplTest {
Yeah, Good suggestion

2021-11-23 08:21 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/ui/tokenlisteditor/TokenListEditorFragment.kt
> +        const val RESULT_TOKEN_LIST_CHANGE = "ExtraTokenListChange"
Good catch.

2021-11-23 08:36 UTC, quocnd commented on shared/src/main/java/io/mvlchain/tada/wallet/shared/data/repository/WalletRepository.kt
> +    }
Repository now is less logic 👍

2021-11-23 08:40 UTC, quocnd commented on shared/src/main/java/io/mvlchain/tada/wallet/shared/data/db/entity/SimpleWalletEntity.kt
> +    @Embedded(prefix = "asset_")
I think we can have a talk about this and improve this later.
As `Index` will speed up your `SELECT` queries but will slow down other queries like `INSERT or UPDATE`

2021-11-23 12:12 UTC, cutehackers commented on app/src/main/java/io/mvlchain/tada/wallet/app/base/IBaseFragment.kt
> +    fun observeResultListeners() = Unit
Oh. okay. I get it

2021-11-23 12:18 UTC, cutehackers commented on shared/src/main/java/io/mvlchain/tada/wallet/shared/data/db/entity/SimpleWalletEntity.kt
> +    @Embedded(prefix = "asset_")
alright I also need to think about pk for asset. okay. I'll make a note of this.

2021-11-24 00:30 UTC, cutehackers approved these changes

2021-11-24 02:31 UTC, merged