[DBC-226] Implement permission guide
mvlchain/mvl-wallet-android pull request #29
Opened 2021-11-20 14:31 UTC by quocnd

## Description
- Implement logic in permission guide

## Note

## Screenshots
https://drive.google.com/file/d/1_IFc3_nYISSfljArZfxSrG36XMaqi3oQ/view?usp=sharing

2021-11-22 05:07 UTC, cutehackers requested changes
- GlobalParam. isPermissionGuideShown is not such a good idea to cache the value because it's already store in preference. But it's ok if it's a temporary use. otherwise you are required to refactor the code. 
- PermissionGuideFragment screen is need to have an argument that makes it navigate to authGuide screen, not from GlobalParam.

2021-11-23 07:41 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/ui/LauncherViewModel.kt
> +                            GlobalParam.isPermissionGuideShown = it.data
I got an issue with load time with previous test.
It took more than 1s to get `PermissionGuideState`. It meant if I pass via intent it always false.
I just retest and can't reproduce this issue now. 😢

2021-11-23 09:28 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/ui/permissionguide/PermissionGuideFragment.kt
> +        if (GlobalParam.isPermissionGuideShown) {
With above reason, but now it's fixed

2021-11-24 05:02 UTC, cutehackers approved these changes

2021-11-24 05:02 UTC, cutehackers commented on app/src/main/java/io/mvlchain/tada/wallet/app/ui/LauncherActivity.kt
> +        const val EXTRA_PERMISSION_GUIDE_SHOWN = "ExtraPermissionGuideState"
Please use the same values as its name

2021-11-24 07:56 UTC, merged