[DBC-168] Codebase for Android
mvlchain/mvl-wallet-android pull request #4
Opened 2021-10-05 03:20 UTC by quocnd

- [Implement codebase for Android](https://mvlchain.atlassian.net/browse/DBC-168)
- Implement [`Wallet`](https://mvlchain.atlassian.net/browse/DBC-111) screen

2021-10-05 07:13 UTC, cutehackers requested changes

2021-10-05 07:13 UTC, cutehackers commented on app/src/main/res/values/dimens.xml
> +    <dimen name="space_large_xxx">40dp</dimen>
Wonderful

2021-10-05 07:13 UTC, cutehackers commented on app/src/main/res/values/pallete.xml
> +    <color name="red">#FF3F3F</color>
wonderful

2021-10-05 07:13 UTC, cutehackers commented on shared/build.gradle
> +    //implementation "androidx.room:room-paging:${versions.ROOM_PAGING}"
you may need this paing library for wallets list.

2021-10-05 07:13 UTC, cutehackers commented on shared/src/main/java/io/mvlchain/tada/wallet/shared/data/api/NetworkConst.kt
> +object NetworkConst {
??? seems it's not necessary for now?

2021-10-05 07:13 UTC, cutehackers commented on shared/src/main/java/io/mvlchain/tada/wallet/shared/di/DatabaseProviders.kt
> +object DatabaseProviders {
please do not maintain provider class for DI

2021-10-05 07:13 UTC, cutehackers commented on shared/src/main/java/io/mvlchain/tada/wallet/shared/di/NetworkProviders.kt
> +object NetworkProviders {
This one as well

2021-10-05 07:45 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/base/BaseFragment.kt
> +abstract class BaseFragment<VB : ViewBinding>() : Fragment(), IBaseFragment, NetworkStateListener {
Correctly, I will remove it

2021-10-05 07:54 UTC, quocnd commented on shared/build.gradle
> +    //implementation "androidx.room:room-paging:${versions.ROOM_PAGING}"
Paging library seems is not really stable with Flow with several `Exprimental` functions. 
Could you take a look at class `NetworkBoundResource` in our source code?. It can handle paging mechanism.

2021-10-05 07:58 UTC, quocnd commented on shared/src/main/java/io/mvlchain/tada/wallet/shared/data/api/NetworkConst.kt
> +object NetworkConst {
I'm gonna using it for paging like `Wallet transfer list`:
GET v1/wallets/{id}/transfers?page={page}&size={size}
But you're right. It should be removed this stage

2021-10-05 08:00 UTC, quocnd commented on shared/src/main/java/io/mvlchain/tada/wallet/shared/di/DatabaseProviders.kt
> +object DatabaseProviders {
It will be removed.

2021-10-05 08:05 UTC, quocnd commented on shared/src/main/java/io/mvlchain/tada/wallet/shared/di/NetworkProviders.kt
> +}
Will move these thing to DI Module

2021-10-05 08:16 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/base/BaseFragment.kt
> +    protected open fun initData() = Unit
This method will be used in some cases that we need to trigger data after  `initView`, `observerViewModels`.
E.g: `initView` (Recycler view) => observerViewModels => Get data from database (in `initData`)

2021-10-05 08:20 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/base/DialogManager.kt
> +    override fun showDialogTwoButton(
Good suggestion!

2021-10-05 08:21 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/base/DialogManager.kt
> +        if (!msg.isNullOrEmpty()) {
Nice, will update it

2021-10-05 08:23 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/base/ToastManager.kt
> +    override fun showShort(msg: String?) {
Cool

2021-10-05 08:24 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/receiver/NetworkReceiver.kt
> +class NetworkReceiver @Inject constructor(
It's a better name

2021-10-05 08:26 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/receiver/NetworkReceiver.kt
> +interface NetworkStateListener {
Good suggestion

2021-10-05 08:48 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/ui/wallet/WalletViewModel.kt
> +            userCase.invoke(type)
- I think we should use a general method for all usecases. and each UseCase just has 1 method, so I think we can use this `operator` method
- userCase will be changed

2021-10-05 08:56 UTC, quocnd commented on app/build.gradle
> -                        "room.expandProjection": "true"
It moved to `build.gradle` in `shared` module

2021-10-05 08:59 UTC, quocnd commented on app/build.gradle
> +        buildConfigField 'String', 'CLIENT_PASSWORD', '""' //TODO Adding CLIENT_PASSWORD
Will update them with config in local.properties

2021-10-05 09:02 UTC, quocnd commented on app/src/main/java/io/mvlchain/tada/wallet/app/base/BaseViewModel.kt
> +    protected suspend fun showLoading() {
Either `showLoading()` or `showLoadingIndicator()` work for me but I prefer `showLoading()` is shorter with enough meaning.

2021-10-05 09:10 UTC, quocnd commented on shared/build.gradle
> +    //implementation "androidx.room:room-paging:${versions.ROOM_PAGING}"
But you may right. Let me do it with paging

2021-10-07 01:28 UTC, cutehackers commented on app/src/main/java/io/mvlchain/tada/wallet/app/di/DatabaseModule.kt
> +        BuildConfig.BASE_URL
What's this?

2021-10-07 01:41 UTC, merged